services:
  keycloak:
    image: bitnami/keycloak:latest
    ports:
      - 8090:8180
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloakdb
      DB_SCHEMA: public
      DB_USER: keycloakuser
      DB_PASSWORD: keycloakpass
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: 123
      KEYCLOAK_HTTP_PORT: 8180
    networks:
      - network
    command: ["start-dev"]
