services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - 8090:8080
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloakdb
      DB_SCHEMA: public
      DB_USER: keycloakuser
      DB_PASSWORD: keycloakpass
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: 123
      KEYCLOAK_HTTP_PORT: 8080
      KEYCLOAK_HTTPS_ENABLED: "false"
    networks:
      - network
    command: ["start-dev"]
networks:
  network:
    external: true
