version: '3'

services:
  keycloak:
    image: bitnami/keycloak:latest
    ports:
      - 8090:8443 # Открываем порт 8443 для HTTPS
    volumes:
      - ./certs:/opt/bitnami/keycloak/certs
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: 123
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_HTTPS_PORT: 8443
      KEYCLOAK_SSL_CERTIFICATE_FILE: /opt/bitnami/keycloak/certs/keycloak.crt
      KEYCLOAK_SSL_CERTIFICATE_KEY_FILE: /opt/bitnami/keycloak/certs/keycloak.key
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloakdb
      DB_SCHEMA: public
      DB_USER: keycloakuser
      DB_PASSWORD: keycloakpass
    networks:
      - network

networks:
  network:
    external: true
