apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: bitnami/keycloak:latest
          env:
            - name: DB_VENDOR
              value: "POSTGRES"
            - name: DB_ADDR
              value: "postgres-service" # Имя сервиса PostgreSQL
            - name: DB_DATABASE
              value: "keycloakdb"
            - name: DB_SCHEMA
              value: "public"
            - name: DB_USER
              value: "keycloakuser"
            - name: DB_PASSWORD
              value: "keycloakpass"
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "123"
            - name: KEYCLOAK_HTTP_PORT
              value: "8180"
          ports:
            - containerPort: 8180

---

apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
spec:
  type: NodePort
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: 8180
      targetPort: 8180
      nodePort: 30080