services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: keycloakdb
      POSTGRES_USER: keycloakuser
      POSTGRES_PASSWORD: keycloakpass
    ports:
      - 5432:5432
    networks:
      - network

volumes:
  postgres_data:

networks:
  network:
    external: true