apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
      - name: adminer
        image: adminer:latest
        env:
        - name: ADMINER_DEFAULT_SERVER
          value: "postgres-service" # Имя сервиса PostgreSQL
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: adminer-service
spec:
  type: LoadBalancer
  selector:
    app: adminer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
