apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-mysql
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin:latest
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: "mysql-deployment"
            - name: PMA_PORT
              value: "3306"
            - name: PMA_ARBITRARY
              value: "1"
            - name: PMA_USER
              value: "appuser"
            - name: PMA_PASSWORD
              value: "apppassword"
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-mysql-service
  labels:
    app: phpmyadmin
spec:
  type: NodePort  # Используйте LoadBalancer при необходимости
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31081  # Порт, доступный снаружи кластера
  selector:
    app: phpmyadmin
