apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            # Переменные окружения для настройки MySQL
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpassword"
            - name: MYSQL_DATABASE
              value: "family"
            - name: MYSQL_USER
              value: "appuser"
            - name: MYSQL_PASSWORD
              value: "apppassword"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data-volume
          ports:
            - containerPort: 3306
      volumes:
        - name: mysql-data-volume
          persistentVolumeClaim:
            claimName: mysql-pvc
---
# Persistent Volume Claim для хранения данных MySQL
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
